function exampleResult = qpExampleData(varargin)
%qpExampleData  Return some example data, as would be generated by qpQuestPlus
%
% Usage:
%     exampleResult = qpExampleData(varargin)
%
% Description:
%     To exercise the functions, it is useful to have a set of example data, as would be returned by qpQuestPlus.
%     We define the example data here.
%
%     exampleResult.paramEstaimtes - Vector of parameter estimates.
%     exampleResult.trialData - Struct array, with each entry
%       trialData(i).stim - Vector of presented stimulus parameters.
%       trialData(i).outcome - Outcome of the trial.
%
% Input:
%     None
%
% Output:
%     exampleResult    The example result.
%
% Optional key/value pairs

% 6/23/17  dhb  Wrote it.

%% Parse input
p = inputParser;
p.parse(varargin{:});

%% Here is the example result from Mathematica, pulled over from the notebook
exampleResultFromMathematica = {{-20, 3.5, 0.5, 0.02}, {{{-18}, 2}, {{-22}, 1}, {{-12}, 2}, {{-13}, 2}, {{-15},2}, ...
    {{-16}, 2}, {{-17}, 2}, {{-18}, 2}, {{-19}, 2}, {{-20}, 2}, {{-22}, 2}, {{-25}, 1}, {{-19}, 1}, {{-16}, 2}, ...
    {{-17}, 2}, {{-18}, 2}, {{-18}, 2}, {{-18}, 1}, {{-16}, 2}, {{-17}, 2}, {{-17}, 2}, {{-17}, 2}, {{-18}, 2}, {{-18}, 2}, ...
    {{-18}, 2}, {{-18}, 2}, {{-18}, 2}, {{-19}, 2}, {{-19}, 2}, {{-19}, 2}, {{-19}, 2}, {{-19}, 2}}};
    

% Parameter estimates
exampleResult.paramEstimates = [exampleResultFromMathematica{1}];

%% Trial data
for ii = 1:length(exampleResultFromMathematica{2})
    exampleResult.trialData(ii).stim = [exampleResultFromMathematica{2}{ii}{1}{:}];
    exampleResult.trialData(ii).outcome = [exampleResultFromMathematica{2}{ii}{2}];
end

end
