% mQuestPlus - dataproc
%
% Data processing utilities for mQuestPlus
%
% qpCounts                      - Convert stimulus data array to stimulus count data array.
% qpData                        - Convert trial data array to stimulus data array.
% qpExampleData                 - Return some example data, as would be generated by qpRun.
% qpProportions                 - Convert stim count data array to stim proportion data array.

